zsebtanar/zsebtanar-proto

- src/admin/components/ExerciseState.jsx
- src/admin/page/excersice-edit/ExerciseForm.jsx
- src/shared/component/general/TextEditor.jsx
- src/shared/component/modal/FileUploadModal.jsx
életem első igazi bugfixe! :dancing_men:
> bug fix: kategória + osztály választás feladatoknál

- src/admin/page/excersice-edit/ExerciseForm.jsx
- src/shared/component/input/RadioInput.jsx
- src/shared/component/userControls/binaryChoice/BinaryChoice.jsx
- src/shared/component/userControls/singleChoice/SingleChoice.jsx
140-es hiba javítása (feladat archiválás + közzététel gombok megjelenítése)
> Zsebtanar proto 140

- src/shared/component/input/RadioInput.jsx
- src/shared/component/userControls/binaryChoice/BinaryChoice.jsx
- src/shared/component/userControls/singleChoice/SingleChoice.jsx
a kulcsokat és az id-ket kellett összehangolni
> Bug fix: radio gombok javítása

- build/config.js
- src/index.ejs
Javított hibajegy: #158 
Változások:
- Smartlook script telepítése
- zsebtanar@gmail.com regisztrálása a honlapon
- [elvileg](https://www.smartlook.com/help/smartlook-user-guide/#recordings-not-showing-the-correct-layout-of-the-page) localhoston nem megy
> #158 - Heatmap telepítése

- src/shared/component/userControls/binaryChoice/BinaryChoiceAdmin.jsx
Javított hibajegy: #162 
Változások: 
- igaz hamis címkék sorrendjének javítása feladatszerkesztőben
> fix 162: igaz hamis címkék sorrendjének javítása

- src/shared/component/input/RadioInput.jsx
- src/shared/component/userControls/singleChoice/SingleChoiceAdmin.jsx
Javított hibajegy: #161
Változások:
- Radio gombok javítása a feladatszerkesztőben
> Zsebtanar proto 161

- src/shared/component/userControls/multiChoice/MultiChoiceAdmin.jsx
Javított hibajegy: #168
Változások: 
- Radio input javítása többszörös feleletválasztónál.
> #168 - Radio input javítása

- package.json
- src/admin/page/excersice-edit/ExerciseForm.jsx
Javított hibajegy: #166 
Változások:
- feladat kulcs javítása klónozásnál
> #166 - Feladat kulcs javítása klónozásnál

- src/shared/component/userControls/singleNumber/SingleNumber.jsx
- src/shared/component/userControls/singleNumber/SingleNumberAdmin.jsx
Javított hibajegy:  #180 
Változások: új pontosság mehatározó mező
> #180 - számmező pontosságának beállítása

- functions/src/exercise/validate/userControls/fractionNumber.js
- functions/src/utils/math.js
- src/shared/component/userControls/UserControl.jsx
- src/shared/component/userControls/UserControlAdmin.jsx
- src/shared/component/userControls/controlTypes.js
- src/shared/component/userControls/fractionNumber/FractionNumber.jsx
- src/shared/component/userControls/fractionNumber/FractionNumberAdmin.jsx
- test/functions/exercise/validate/fractionNumber.spec.js
Javított hibajegy: #181 
Változások: törtszám mező
> #181 - törtszám mező + validáció

- docs/contribution.md
- docs/issue_template.md
- docs/pull_request_template.md
kisebb módosítások a templat-ekben, valamint extra leírás a feladatlétrehozáshoz
> Github issue/pull-request template frissítés

- src/admin/page/excersice-edit/SubTaskList.jsx
Javított hibajegy: #172 
Változások: részfeladat törlése és felvétele után autómatikusan frissűl a részfeladatok neve és sorrendje, így nem fordulhat elő, hogy kettőnek ugyan az legyen a neve
> #172 - részfeladat név és rendezés frissítése lista módosításkor

- src/shared/component/modal/MarkdownHelpModal.jsx
- src/shared/store/actions/modal.js
Javított hibajegy: #136 
Változások: Markdown súgó modal javítása
> #136 - Markdown súgó modal javítása

- functions/src/exercise/state/index.js
- src/admin/page/excersice-edit/ExerciseForm.jsx
- src/shared/component/general/Button.jsx
**Javított hibajegy:** #178 
- feladat törlés bármilyen állapotből (nem csak vázlat)
- feladat admin fejléc átrendezés
- `icon` attribute a gomb elemen
> #178 - feladat törlés bármilyen állapotból

- src/admin/page/ExerciseList.jsx
- src/shared/main.scss
**Javított hibajegy:** #188
- feladat lista témakör oszlopának javítása
- feladat törlés funkció eltávolítása (csak a feladat szerkesztőből lehetséges)
> #188 - feladat lista témakör oszlopának javítása

- src/shared/component/userControls/multiChoice/MultiChoiceAdmin.jsx
Javított hibajegy: #168 
Változások: 
- Megoldás frissítésének javítása a state-ben
> #168 - Igaz-hamis admin mező javítása

- package-lock.json
- package.json
- src/admin/page/excersice-edit/SubTaskList.jsx
- src/admin/page/excersice-edit/UserControlItem.jsx
- src/admin/page/excersice-edit/UserControlList.jsx
- src/shared/component/general/Sortable.jsx
- src/shared/component/general/TabNav.jsx
- src/shared/util/fn.js
**Javított hibajegy:** #14 
- részfeladatok rendezéss drag&drop-al
- megoldások rendezéss drag&drop-al
> #14 - drag & drop funkció implementálása az feledat szerkesztőben

- src/shared/component/userControls/singleNumber/SingleNumber.jsx
**Javított hibajegy:** #196 
- súgó szöveg megjelenítése a szám beviteli mező alatt (csak ha a tizedesjegy pontosság > 0)
> #196 - szám mező tizedesjegy pontosság megjelenítése

- src/admin/page/excersice-edit/HintItem.jsx
- src/admin/page/excersice-edit/HintList.jsx
- src/admin/page/excersice-edit/SubTask.jsx
- src/admin/page/excersice-edit/UserControlItem.jsx
- src/admin/store/exerciseEdit.js
- src/shared/component/modal/Overlay.jsx
**Javított hibajegy:** #216 
- útmutatók rendezése drag&drop-al
- kis UI egységesítés
> #216 - útmutatók rendezése drag&drop-al

- functions/src/exercise/validate/validator.js
- functions/src/utils/math.js
- test/functions/exercise/validate/fractionNumber.spec.js
**Javított hibajegy:** #192 
- validáció javítás 
- pár extra teszt
> #192 - törtszám validáció javítása

- functions/package-lock.json
- functions/package.json
- functions/src/exercise/crud/index.js
- package.json
- src/admin/page/excersice-edit/ExerciseForm.jsx
- src/admin/store/exerciseEdit.js
- src/index.ejs
- src/shared/services/exercise.js
**Javított hibajegy:** #227 
-mentés javítása
> #227 - mentés javítása

- src/shared/page/exercise/Exercise.jsx
- src/shared/store/exercise.js
**Javított hibajegy:** #123 
- nem létező feladat kezelése publikus oldalon
> #123 - nem létező feladat kezelése publikus oldalon

- src/admin/page/excersice-edit/ExerciseForm.jsx
**Javított hibajegy:** #177 
- feladat nehézségválasztó javítása
> #177 - feladat nehézségválasztó javítása

- src/shared/component/modal/ProviderSignUp.jsx
- src/shared/component/modal/SignUpModal.jsx
- src/shared/store/actions/auth.js
- src/shared/store/reducers/session.js
**Javított hibajegy:** #97 
- regisztrációs mezők validálása
- javított töltés jelzés
> #97 - regisztrációs mezők validálása és javított töltés jelzés

- src/public/nav/Header.jsx
- src/public/nav/SideNav.jsx
**Javított hibajegy:** #198 
- admin  feladatlista kezdőoldal
> #198 - feladatlista kezdőoldal

- src/public/component/DonateButton.jsx
- src/public/page/Home.jsx
**Javított hibajegy:** #249 
Paypal gomb hozzáadása a kezdőlaphoz
> Paypal gomb hozzáadása

- src/admin/page/excersice-edit/UserControlList.jsx
- src/shared/component/userControls/singleChoice/SingleChoiceAdmin.jsx
**Javított hibajegy:** #243 
- hiányzó képek javítása
> #243 - hiányzó képek javítása

- .circleci/config.yml
> npm ci nem tamogatott circle ci-on

- functions/package.json
> fix cloud function dependencies

- package-lock.json
- package.json
- a prettier beállítások mostantól minden eszköz (pre-commit hook, IDE, stb.)  elérhető
> prettier kód formázó globális konfiguráció beállítása

- src/public/page/Profile.jsx
- src/shared/component/modal/ConfirmModal.jsx
- src/shared/component/modal/base/Dialog.jsx
- src/shared/component/modal/base/DialogBody.jsx
- src/shared/component/modal/base/DialogClose.jsx
- src/shared/component/modal/base/DialogFooter.jsx
- src/shared/component/modal/base/DialogHeader.jsx
- src/shared/services/user.js
- src/shared/store/actions/auth.js
- src/shared/store/actions/modal.js
**Javított hibajegy:** #266 
- confirm modál bevezetése
- felhasználói profil törlése lehetőség
> #266 - felhasználói profil törlése

- src/client-common/component/general/Markdown.tsx
- src/client-common/component/modal/AlertModal.tsx
- src/client-common/component/modal/ConfirmModal.tsx
- src/client-common/component/modal/CookieModal.tsx
- src/client-common/component/modal/EquationHelpModal.tsx
- src/client-common/component/modal/ExerciseImageDialog.tsx
- src/client-common/component/modal/ExerciseResultModal.tsx
- src/client-common/component/modal/FeedbackModal.tsx
- src/client-common/component/modal/FileUploadModal.tsx
- src/client-common/component/modal/InputModal.tsx
- src/client-common/component/modal/MarkdownHelpModal.tsx
- src/client-common/component/modal/Overlay.tsx
- src/client-common/component/modal/ProviderSignUp.tsx
- src/client-common/component/modal/ResetPasswordModal.tsx
- src/client-common/component/modal/SignInModal.tsx
- src/client-common/component/modal/SignUpModal.tsx
- src/client-common/component/modal/UserControlModal.tsx
- src/client-common/component/util/DynamicComponent.tsx
- src/client-common/store/actions/auth.ts
- src/client-common/store/actions/modal.ts
- src/client-common/store/reducers/modal.ts
- src/shared/types.d.ts
- tslint.json
**Javított hibajegy:** #98 
- elefeljtett jelszó modál
> #98 - elefeljtett jelszó modál

- src/client-common/component/general/SideNavLink.tsx
- src/client-public/nav/SideNav.tsx
**Javított hibajegy:** #271 
- mobil menü javítás a publikus oldalon
> #271 - mobil menü javítás a publikus oldalon

- src/client-admin/Routes.tsx
- src/client-admin/page/Home.tsx
- src/client-common/component/general/dropdown/DropdownToggle.tsx
- src/client-common/component/modal/SignInModal.tsx
- src/client-common/style/main.scss
**Javított hibajegy:** #289 
- belenketzési modal javítása
> #289 - belenketzési modal javítása

- src/client-common/component/general/Markdown.tsx
- src/shared/markdown/image-resource/index.ts
- src/shared/util/string.ts
- test/server/utils/markdown.spec.ts
**Javított hibajegy:** #303 
- keresett szó kiemelés javítása a kereső oldalon
> #303 - keresett szó kiemelés javítása a kereső oldalon

- src/client-common/index.ejs
- src/client-common/page/Workarounds.tsx
- src/client-common/page/exercise/Exercise.scss
- src/client-common/page/exercise/Exercise.tsx
- src/client-common/page/exercise/SubTask.tsx
- src/client-common/style/_bootstrap.scss
- src/client-common/style/main.scss
- src/client-public/Routes.tsx
- src/client-public/component/DonateButton.tsx
- src/client-public/nav/Header.tsx
- src/client-public/page/ExercisesByGrade.tsx
- src/client-public/page/ExercisesByTopic.tsx
- src/client-public/page/Home.tsx
- src/client-public/page/Search.tsx
- src/client-public/public.tsx
- src/server/exercise/validate/validator.ts
**Javított hibajegy:** #311 
- feladatmegoldo UX frissítés
> #311 - feladatmegoldo UX frissítés

- src/client-admin/nav/Header.tsx
- src/client-common/component/error/ShwoError.tsx
- src/client-common/component/general/Button.tsx
- src/client-common/page/Page404.tsx
- src/client-common/page/exercise/Exercise.tsx
- src/client-common/services/exercise.ts
- src/client-common/store/exercise.ts
- src/client-common/util/error.ts
- src/client-public/component/CookieConsent.tsx
- src/client-public/nav/Header.tsx
- src/client-public/page/ExercisesByGrade.tsx
- src/client-public/page/ExercisesByTopic.tsx
- src/shared/util/fn.ts
**Javított hibajegy:** #330 
- fix 404 oldalak
> #330 - fix 404 oldalak

- src/client-admin/admin.tsx
- src/client-admin/nav/SideNav.tsx
- src/client-common/component/modal/EquationHelpModal.tsx
- src/client-common/component/modal/ExerciseImageDialog.tsx
- src/client-common/component/modal/InputModal.tsx
- src/client-common/component/modal/MarkdownHelpModal.tsx
- src/client-common/component/modal/ProviderSignUp.tsx
- src/client-common/component/modal/SignInModal.tsx
- src/client-common/component/modal/SignUpModal.tsx
- src/client-common/component/modal/UserControlModal.tsx
- src/client-common/style/_bootstrap-public.scss
- src/client-common/style/public.scss
- src/client-public/Routes.tsx
- src/client-public/nav/Header.scss
- src/client-public/nav/Header.tsx
- src/client-public/nav/SideNav.scss
- src/client-public/nav/SideNav.tsx
- src/client-public/public.tsx
**Javított hibajegy:** #360 
- Fejléc rögzítése az oldal tetején
- beúszó menü animáció mobilon
- dialóg bezárás gombok javítása
> zsebtanar-proto-360 Fejléc rögzítése az oldal tetején

- package.json
hiányzó szerver függőség javítása
> fix server dependencies

- build/config.js
**Javított hibajegy:** #379 
- CSP lista frissítése
> zsebtanar-proto-379 CSP frissítése a sentry log alapján

- build/config.js
**Javított hibajegy:** #386
- config.json javítása
> tesz szerver hibajavítása

- src/client-common/store/reducers/session.ts
**Javított hibajegy:** #388
- admin oldalátirányítások javítása
> zsebtanar-proto-388 - admin oldal átirányítás javítása

- src/client-common/page/exercise/Exercise.tsx
**Javított hibajegy:** -
- a feladatmegoldás sikerének visszajelzése nem tartalmaz elgépelést
> helyesírás javítása

- build/config.js
- adatvédelmi szabályzat frissítése
> adavédelmi szabályzat frissítése

- build/config.js
- adatvédelmi szabályzat frissítése
> adatvédelmi szabályzat V3

- firebase.json
- src/server/exercise/validate/userControls/_test/numberList.spec.ts
- src/server/exercise/validate/userControls/numberList.ts
- src/shared/types.d.ts
**Javított hibajegy:** #395 
- számlista törtszámok validációjának javítása
> #395 - számlista törtszámok validációjának javítása

- src/client-public/page/ExercisesByGrade.tsx
- src/client-public/page/ExercisesByTopic.tsx
**Javított hibajegy:** #418 
- Publikus kategória oldal nem omlik össze has az egyik feladatnak nincsenek tag-jei
> #418 - kategória oldalak javítása

- src/client-common/component/userControls/common/DecimalAccuracyWarning.tsx
- src/client-common/component/userControls/numberList/NumberList.tsx
- src/client-common/component/userControls/singleNumber/SingleNumber.tsx
- src/client-public/page/ExercisesByGrade.tsx
- src/client-public/page/ExercisesByTopic.tsx
- #382 - szamlista figyelmeztetes hozzaadasa
- #418 - kategória oldalak javítása
> Release - 2019.05.07.

- build/config.js
- build/post-build.js
- firebase.json
- resources/sitemap.xml
**Javított hibajegy:** #345 
- robot.txt
- sitemap.xml
> #345 - add robot.txt and minimal sitemap.xml

- src/client-common/style/public.scss
- src/client-public/component/YouTubeEmbed.tsx
- src/client-public/nav/Footer.tsx
- src/client-public/page/Home.tsx
**Fixed issue:** #443 
**Modifications**
- latest Youtube video appears on the home page
- updated footer
- Youtube link in the footer
> zsebtanar-proto-443 Add Youtube reference to the site

- src/client-common/style/public.scss
- src/client-public/component/YouTubeEmbed.tsx
- src/client-public/nav/Header.tsx
- src/client-public/page/Profile.tsx
**Javított hibajegy:** #407 
- Profile szövegek magyarosítása
- apró design javítások
> zsebtanar-proto-407 Profil link magyarosítás

- docs/issue_template.md
> Update issue template

- build/config.js
- build/emulator.sh
- build/webpack.client.js
- package-lock.json
- package.json
- src/client-admin/page/exerciseEdit/HintItem.tsx
- src/client-admin/page/exerciseEdit/SubTaskList.tsx
- src/client-admin/page/exerciseEdit/UserControlItem.tsx
- src/client-admin/store/index.ts
- src/server/exercise/crud/search.ts
- src/server/exercise/crud/utils.ts
- src/server/exercise/hints/_test/hints.spec.ts
- src/server/exercise/hints/nextHint.ts
- src/server/exercise/model.ts
- src/server/exercise/state/index.ts
- src/server/exercise/validate/userControls/_test/binaryChoice.spec.ts
- src/server/exercise/validate/userControls/_test/fractionNumber.spec.ts
- src/server/exercise/validate/userControls/_test/numberList.spec.ts
- src/server/exercise/validate/userControls/_test/singleChoice.spec.ts
- src/server/exercise/validate/userControls/_test/singleNumber.spec.ts
- src/server/exercise/validate/userControls/binaryChoice.ts
- src/server/exercise/validate/userControls/multiChoice.ts
- src/server/exercise/validate/userControls/numberList.ts
- src/server/exercise/validate/userControls/simpleText.ts
- src/server/exercise/validate/validator.ts
- src/server/index.ts
- src/shared/types.d.ts
- src/shared/util/fn.ts
- tsconfig.json
Add firebase server emulator and few fixes
> add firebase server emulator

- src/client-common/component/userControls/simpleText/SimpleText.tsx
**Issue number:** #453 
**Changelog:**
- fix user single text input
> zsebtanar-proto-453 fix single text input

- src/client-common/style/public.scss
- src/client-public/page/Home.tsx
**Issue number:** #471
**Changelog:**
- Add notification about our new feedback form
> zsebtanar-proto-471 Add notification about our new feedback form

- src/shared/script/shared-code/mathUtils.spec.ts
- src/shared/script/shared-code/mathUtils.ts
- src/shared/script/shared-code/utils.ts
**Changelog:**
- feature: convert integers to roman numerals (pocketlisp)
> feature: convert integers to roman numberals

- src/shared/script/shared-code/langUtils.spec.ts
- src/shared/script/shared-code/langUtils.ts
**Issue number:** #537 
**Changelog:**
- convert fractions to text
> convert fractions to text

- src/shared/script/shared-code/langUtils.spec.ts
- src/shared/script/shared-code/langUtils.ts
**Issue number:** #558 
**Changelog:**
- convert decimal numbers to text
> convert decimals to text

- src/client/exercise/components/userControls/singleChoice/SingleChoiceAdmin.tsx
- src/client/exercise/components/userControls/singleNumber/SingleNumberAdmin.tsx
> remove extra parantheses

- src/client/app-public/pages/Privacy.tsx
- src/client/app-public/pages/Terms.tsx
> Add privacy policy & terms and conditions

- src/client/classification/pages/ClassificationsAdmin.tsx
- src/server/index.ts
- src/server/middlewares/errorHandler.ts
- src/server/middlewares/firebaseToken.ts
- src/server/utils/HandlerError.ts
- src/server/utils/authorization.ts
- src/server/utils/pocketLisp.ts
- src/shared/markdown/youtube-embed/index.ts
- src/shared/markdown/youtube-embed/youtubeEmbed.spec.ts
- update serverside logging
- fix youtube embed Markdown parser
- fix exercise counter on classification admin page
> fix: minor issues

- src/client/app-admin/admin.scss
- src/client/generic/components/markdown/MarkdownBase.scss
> fix: markdown text align to center feature

- src/shared/script/shared-code/mathUtils.spec.ts
- src/shared/script/shared-code/mathUtils.ts
- src/shared/script/shared-code/utils.ts
**Issue number:** #614 
**Changelog:**
- add gcd function
> feature: add gcd function

- src/client/exercise/components/admin/ExerciseFormSubTasks.tsx
- src/client/exercise/components/userControls/singleNumber/SingleNumberAdmin.tsx
- use false for isDynamic for each field type by default
- convert number filed solution into string
issue: #608
> fix: exercise creation with static number field
